-- QIALITY CHECKING THE SILVER.erp_loc_a101 TABLE

-- LOOKING FOR UNWANTED SPACES

SELECT CID
FROM Silver.erp_loc_a101
WHERE CID != TRIM(CID)

SELECT REPLACE(TRIM(CID),'-','') AS CID
FROM Silver.erp_loc_a101

SELECT * FROM Silver.erp_loc_a101

-- SURVEYING CTRY COLUMN
-- DATA STANDARDIZATION AND CONSISTENCY

SELECT DISTINCT CNTRY
FROM Silver.erp_loc_a101
ORDER BY CNTRY