-- CHECKING THE SILVER.erp_loc_a101 TABLE

-- LOOKING FOR UNWANTED SPACES

SELECT CID
FROM Bronze.erp_loc_a101
WHERE CID != TRIM(CID)

SELECT REPLACE(TRIM(CID),'-','') AS CID
FROM Bronze.erp_loc_a101

SELECT * FROM Bronze.erp_loc_a101

-- SURVEYING CTRY COLUMN
-- DATA STANDARDIZATION AND CONSISTENCY

SELECT DISTINCT CNTRY,
	CASE 
		WHEN CNTRY = 'DE' THEN 'Germany'
		WHEN CNTRY IN ('US','USA') THEN 'United States'
		WHEN CNTRY = '' OR CNTRY IS NULL THEN 'n/a'
		ELSE CNTRY
	END CNTRY1
FROM Bronze.erp_loc_a101
ORDER BY CNTRY