-- CHECKING FOR ERRORS

	-- CHECKING FOR NULLS, MISSING VALUE

	SELECT *
	FROM Bronze.erp_px_cat_g1v2
	WHERE ID IS NULL OR
			CAT IS NULL OR
			SUBCAT IS NULL OR
			MAINTENANCE IS NULL

-- CHECKING THE ID COLUMN

SELECT ID
FROM Bronze.erp_px_cat_g1v2
WHERE ID <> TRIM(ID)

SELECT ID
FROM Bronze.erp_px_cat_g1v2

SELECT * FROM Bronze.erp_px_cat_g1v2
WHERE ID NOT IN ( SELECT cat_id FROM Silver.crm_prd_info)

SELECT cat_id FROM Silver.crm_prd_info WHERE cat_id = 'CO-PD'

-- CHECKING THE CATEGORIES COLUMN
-- DATA STANDARDIZATION & CONSISTENCY
-- CHECKING FOR UNWANTED SPACES

SELECT DISTINCT CAT
FROM Bronze.erp_px_cat_g1v2
WHERE CAT <> TRIM(CAT)

-- CHECKING THE SUB CATEGORIES COLUMN
-- DATA STANDARDIZATION & CONSISTENCY

SELECT DISTINCT SUBCAT
FROM Bronze.erp_px_cat_g1v2
WHERE SUBCAT <> TRIM(SUBCAT)

--CHECKING THE MAINTENANCE COLUMN
-- DATA STANDARDIZATION & CONSISTENCY

SELECT DISTINCT MAINTENANCE
FROM Bronze.erp_px_cat_g1v2
WHERE MAINTENANCE <> TRIM(MAINTENANCE)


select * from Silver.crm_prd_info
select * from Bronze.erp_px_cat_g1v2

-- QUALITY CHECK & HEALTH SURVEY

SELECT * FROM Silver.erp_px_cat_g1v2